"""Recreated initial migration

Revision ID: 35572a4fbc26
Revises: 2b073390016d
Create Date: 2024-10-10 11:05:37.308841

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '35572a4fbc26'
down_revision = '2b073390016d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE coaches CASCADE')
    op.execute('DROP TABLE sessions CASCADE')
    op.execute('DROP TABLE clients CASCADE')
    op.execute('DROP TABLE coach_clients CASCADE')

    # op.drop_table('coaches', cascade=True)
    # op.drop_table('sessions', cascade=True)
    # op.drop_table('clients', cascade=True)
    # op.drop_table('coach_clients', cascade=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_clients',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('coach_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='fk_coach_clients_client_id_clients'),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], name='fk_coach_clients_coach_id_coaches'),
    sa.PrimaryKeyConstraint('id', name='coach_clients_pkey')
    )
    op.create_table('clients',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('clients_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('goals', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='clients_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('goal_progress', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('paid_status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('coach_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='fk_sessions_client_id_clients'),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], name='fk_sessions_coach_id_coaches'),
    sa.PrimaryKeyConstraint('id', name='sessions_pkey')
    )
    op.create_table('coaches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('specialization', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='coaches_pkey'),
    sa.UniqueConstraint('username', name='coaches_username_key')
    )
    # ### end Alembic commands ###
