"""added paid status persist on backend

Revision ID: 1b7c0698fb54
Revises: ce2e93506a47
Create Date: 2024-09-17 15:16:43.781560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b7c0698fb54'
down_revision = 'ce2e93506a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('paid_status')

    # ### end Alembic commands ###
