"""fixed sessions

Revision ID: ce2e93506a47
Revises: 40c3d78e9745
Create Date: 2024-09-17 14:47:55.318537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce2e93506a47'
down_revision = '40c3d78e9745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('specialization',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('coach_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('coach_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.alter_column('specialization',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    op.create_table('admins',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_admins'),
    sa.UniqueConstraint('username', name='uq_admins_username')
    )
    # ### end Alembic commands ###
