"""empty message

Revision ID: d65b9afab74a
Revises: 1b7c0698fb54
Create Date: 2024-10-08 06:28:24.203196

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd65b9afab74a'
down_revision = '1b7c0698fb54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions', cascade=True)
    op.drop_table('coach_clients', cascade=True)
    op.drop_table('coaches', cascade=True)
    op.drop_table('clients', cascade=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('clients_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('goals', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_clients'),
    postgresql_ignore_search_path=False
    )
    op.create_table('coaches',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('coaches_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('specialization', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_coaches'),
    sa.UniqueConstraint('username', name='uq_coaches_username'),
    postgresql_ignore_search_path=False
    )
    op.create_table('coach_clients',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('coach_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='fk_coach_clients_client_id_clients'),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], name='fk_coach_clients_coach_id_coaches'),
    sa.PrimaryKeyConstraint('id', name='pk_coach_clients')
    )
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('goal_progress', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('coach_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('paid_status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='fk_sessions_client_id_clients'),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], name='fk_sessions_coach_id_coaches'),
    sa.PrimaryKeyConstraint('id', name='pk_sessions')
    )
    # ### end Alembic commands ###
